name: Build Windows Installer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r build_requirements.txt
        
    - name: Create assets directory
      run: |
        if (!(Test-Path -Path "assets")) {
            New-Item -ItemType Directory -Path "assets" -Force
        }
        if (!(Test-Path -Path "assets/icon.ico")) {
            Set-Content -Path "assets/icon.ico" -Value "Creating placeholder icon..."
        }
      shell: pwsh
        
    - name: Build executable
      run: python build.py
      
    - name: Download Inno Setup
      run: |
        Invoke-WebRequest "https://files.jrsoftware.org/is/6/innosetup-6.2.2.exe" -OutFile "innosetup.exe"
        
    - name: Install Inno Setup
      run: |
        Start-Process -FilePath "innosetup.exe" -ArgumentList "/VERYSILENT /SUPPRESSMSGBOXES /NORESTART" -Wait
        
    - name: Create installer directory
      run: |
        if (!(Test-Path -Path "installer")) {
            New-Item -ItemType Directory -Path "installer" -Force
        }
      shell: pwsh
      
    - name: Build installer
      run: |
        & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer.iss
        
    - name: Upload installer artifact
      uses: actions/upload-artifact@v4
      with:
        name: ChiropracticManager-Setup
        path: installer/ChiropracticManager_Setup.exe 