name: Build Windows Installer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15  # Add overall timeout
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r build_requirements.txt
        
    - name: Create assets directory and icon
      run: |
        if (!(Test-Path -Path "assets")) {
            New-Item -ItemType Directory -Path "assets" -Force
        }
        python -c "from PIL import Image; img = Image.new('RGB', (256, 256), color='blue'); img.save('assets/icon.ico', format='ICO')"
      shell: pwsh
        
    - name: Build executable
      run: python build.py
      
    - name: Download Portable Inno Setup
      run: |
        $setupUrl = "https://files.jrsoftware.org/is/6/innosetup-6.2.2.zip"
        $setupFile = "innosetup.zip"
        
        Write-Host "Downloading Portable Inno Setup..."
        Invoke-WebRequest -Uri $setupUrl -OutFile $setupFile -TimeoutSec 30
        
        Write-Host "Extracting Inno Setup..."
        Expand-Archive -Path $setupFile -DestinationPath "innosetup" -Force
      shell: pwsh
      
    - name: Build installer
      run: |
        .\innosetup\ISCC.exe installer.iss
      shell: pwsh
      
    - name: Upload installer
      uses: actions/upload-artifact@v4
      with:
        name: ChiropracticManager-Installer
        path: installer/ChiropracticManager-Setup.exe 