name: Build Windows Installer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15  # Add overall timeout
    env:
      DEVELOPER_NAME: "Naveed Jawaid"
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pywin32  # Required for Windows-specific features
        
    - name: Create assets directory
      run: |
        if (!(Test-Path -Path "assets")) {
            New-Item -ItemType Directory -Path "assets" -Force
        }
        Copy-Item "src/assets/logo.png" -Destination "assets/logo.png" -Force
        # Convert logo to ico format for Windows
        python -c "from PIL import Image; img = Image.open('assets/logo.png'); img.save('assets/icon.ico', format='ICO')"
      shell: pwsh
        
    - name: Build executable
      run: python build.py
      
    - name: Install Inno Setup
      run: |
        choco install innosetup --no-progress -y
      shell: pwsh
      
    - name: Build installer
      run: |
        & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer.iss
      shell: pwsh
      
    - name: Upload installer
      uses: actions/upload-artifact@v4
      with:
        name: ChiropracticManager-Installer
        path: installer/ChiropracticManager_Setup.exe 